### ISSUE TITLE
DMA Timeout not Run

### ISSUE THREAD

**Issue by yetkieu846** [akospasztor/stm32-dma-uart#2]
I am using STM32F4 disco Kit. I am trying your code but DMA timeout Event not run. Interrupt only call when Buffer is full. What is the issues?

**Comment by yetkieu846** [comment]
SURE!
My code Using HAL Lib and need

**Comment by akospasztor** [comment]
Hi, I'd recommend to check and verify the followings:
- Is your SysTick configured properly? 
- Is your UART (and the appropriate UART peripheral) configured properly with the DMA? 
- Is the UART IDLE interrupt enabled?
- Overall the code is correctly ported to the F4xx MCU?

**Comment by yetkieu846** [comment]
Yes, thank for your recommend. I have found the issue. "Is the UART IDLE interrupt enabled?" that right.
i used __HAL_UART_ENABLE_IT(&huart1, UART_IT_IDLE); and it work perfectly

**Comment by akospasztor** [comment]
I'm glad that you found the issue and managed to get it work.

**Comment by ghost** [comment]
Hi,

It's totally safe to remove timeout and process data immendiately after IDLE interrupt happend? I don't really need timeout, I need to process the data as fast as I can. It would be still better than using byte-to-byte interrupt method for data processing.

**Comment by akospasztor** [comment]
It depends on your application. If you receive data from your peripheral/device which is guaranteed that there is not a single delay between characters in a burst/message, then you can rely simply on the IDLE interrupt. If not, then this approach is not safe. 

Regarding the "byte-to-byte" interrupt question: it again depends on your application. If you can process data in chunks as well (and you don't have to wait until you receive each byte of the incoming message) then maybe it is a better approach. If not, then not. But in general, using DMA will reduce your overall CPU utilization.
